第九章/cart/urls.py
from django.conf.urls import url
from  . import views

app_name='cart'

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

第九章/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('copons/'),include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('',include('shop.urls',namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

第九章/shop/urls.py
from django.conf.urls import url
from .import views
app_name='shop'
urlpatterns=[
    url(r'^$',views.product_list,name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
]

第九章/shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel,TranslatedFields

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)

    # translations = TranslatedFields(
    #     name_t=models.CharField(max_length=200, db_index=True),
    #     slug_t = models.SlugField(max_length=200, db_index=True, unique=True)
    # )

    class Meta:
        ordering=('name',)
        verbose_name='categroy'
        verbose_name_plural='categories'

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True)
    image=models.ImageField(upload_to="product/%Y/%m/%d",blank=True)
    description=models.TextField(blank=True)
    # translations = TranslatableModel(
    #     name_t=models.CharField(max_length=200, db_index=True),
    #     slug_t = models.SlugField(max_length=200, db_index=True),
    #     description_t=models.TextField(blank=True),
    # )
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.PositiveIntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created',)
        index_together=(('id','slug'),)

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])


第九章/shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
from .recommender import Recommenter

# Create your views here.

def product_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter(available=True)
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=products.filter(category=category)
    return render(request,'shop/product/list.html',
                  {'category':category,'categories':categories,'products':products})

def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    r = Recommenter()
    recommented_products = r.suggest_products_for([product],4)
    return  render(request,'shop/product/detail.html',{'product':product,
                                                       'casrt_product_form':cart_product_form,
                                                       'recommented_products':recommented_products})

第九章/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{%  if category %}{{ category.title }}{% else %} Product{% endif %}{% endblock %}
{% block content %}
<div  class="col-sm-6 col-md-10">
    {% if product.image %}<img src="{{ product.image.url }}" style="width: 300px;height: 300pt" align="left"> {% else %}{{ static }}{% endif %}

    <h1>{{ product.name }}</h1>
<h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a> </h2>
{{ product.description|linebreaks }}
<p class="badge" >${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ casrt_product_form }}
            {% csrf_token %}
            <input type="submit" value="{% trans "Add to cart" %}">
        </form>
</div>
{% endblock %}

第九章/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{%  load i18n %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}
{% endblock %}
{% block content %}
    <div class="navbar">
    <h3>{% trans "Categories" %}</h3>
    <ul class="nav nav-pills nac-stacked">
        <li {% if not category %} class="active" {% endif %}>
        <a class="label label-default" href="{% url "shop:product_list" %}">{% trans "ALL" %}</a>
        </li>
    {% for c in categories %}
        <li {% if category.slug == c.slug %} class="active"{% endif %}>
        <a href="{{ c.get_absolute_url }}" class="label label-default" >{{ c.name }}</a>
        </li>
    {% endfor %}
    </ul>
    </div>
    <div class="list-group">
    <h1>{%  if category %}{{ category.name }}{% else %}Product{% endif %}</h1>
    {%  for product in products %}
        <div class="list-group-item">
        <a href="{{ product.get_absolute_url }}">
            {%  if product.image %}<img src="{{ product.image.url }}"style="width: 200pt;height: 200pt">{% else %} {{ static }} {% endif  %}
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <p>${{ product.price }}</p>
        </div>
    {% endfor %}

    </div>
{% endblock %}