第四章/account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import  login,logout,logout_then_login,password_change_done,password_change
from django.contrib.auth.views import  password_reset,password_reset_done,password_reset_confirm,password_reset_complete
app_name='account'
urlpatterns=[
    #url(r'^login/$',views.user_login,name='login')
    url(r'^login/$',login,name='login'),
    url(r'^logout/$',logout,name='logout'),
    url(r'^logout-then-login/$',logout_then_login,
        name='logout_then_login'),
    url(r'^$',views.dashboard,name='dashboard'),
    url(r'^password-change/$',password_change,
        {'post_change_redirect': 'account:password_change_done'},
        name='password_change'),
    url(r'^password-change/done/$',password_change_done,name='password_change_done'),
    url(r'^password-reset/$',password_reset,{'post_reset_redirect': 'account:password_reset_done'},
        name='password_reset'),
    url(r'^password-reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',password_reset_confirm,
        {'post_reset_redirect':'account:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$',password_reset_complete,name='password_reset_complete'),
    url(r'^register/$',views.register,name='register'),
    url(r'^edit/$',views.edit,name='edit'),
]

第四章/account/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date_of_birth=models.DateField(blank=True,null=True)
    photo=models.ImageField(upload_to='user/%y/%m/%d',blank=True)

    def __str__(self):
        return 'Profile for user'.format(self.user.username)

第四章/account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from .models import Profile
from .forms import LoginForm,UserRegistrationForm,ProfileEditForm,UserEditForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def user_login (request):
    if request.method=="POST":
        form=LoginForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            user=authenticate(username=data['username'],password=data['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return  HttpResponse('Authenticate Successfully')
                else:
                    return  HttpResponse('Disable Account')
            else:
                return HttpResponse('Invalid login')
    else:
        form=LoginForm()

    return render(request,'account/login.html',{'form':form})

@login_required
def dashboard(request):
    return render(request,
                  'account/dashboard.html',
                  {'section':"dashboard"})

def register(request):
    if request.method=='POST':
        user_form=UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile=Profile.objects.create(user=new_user)
            return render(request,'account/register_done.html',
                        {'new_user':new_user})
    else:
        user_form=UserRegistrationForm()
    return render(request,'account/register.html',
                    {'user_form':user_form})
@login_required
def edit(request):
    if request.method=="POST":
        user_form =UserEditForm(instance=request.user,data=request.POST,files=request.FILES)
        profile_form=ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Profile updated successfully')
        else:
            messages.error(request,"Error updated your profile")
    else:
        user_form=UserEditForm(instance=request.user)
        profile_form=ProfileEditForm(instance=request.user.profile)
    return render(request,'account/edit.html',{'user_form':user_form,
                                               'profile_form':profile_form})

第四章/account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
<script src="{% static "js/bootstrap.js" %}"></script>
<script>
var csrftoken = $.cookie('csrftoken');
  function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
  beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
  }
}
});
    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });
</script>
</head>
<body>
<div id="header" class="container-fluid"  role="navigation">
    <span class="nav navbar-brand">Bookmarks</span>
    {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li {% if section|safe == "dashboard" %} class="active" {% endif %}>
        <a href="{% url "account:dashboard" %}">My dashboard</a>
        </li>
     <li {% if section|safe == "images" %}class="active"{% endif %}>
        <a href="#">Images</a>
      </li>
      <li {% if section|safe == "people" %}class="active"{% endif %}>
        <a href="#">People</a>
       </li>
      </ul>
     {% endif %}
     <span class="navbar-brand" >
       {% if request.user.is_authenticated %}
         Hello {{ request.user }},
         <a href="{% url "account:logout" %}">Logout</a>
       {% else %}
         <a href="{% url "account:login" %}">Log-in</a>
       {% endif %}
     </span>
</div>'
{%  if messages %}
<ul class="messagelist">
    {% for message in messages %}
    <li class="{{ message.tage }}">{{ message|safe }}
    <a href="#" class="close"></a>
    </li>
    {% endfor %}
</ul>
{% endif  %}
<div id="content">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>