第三章/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed
app_name='blog'
urlpatterns=[
    url(r'^$',views.post_list,name='post_list'),
    url (r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),
    #url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/',views.post_share,name='post_share'),
    url(r'feed/$',LatestPostFeed(),name='post_feed'),
    url(r'^search/$',views.post_search,name='post_search'),
]

第三章/mysite/urls.py
from django.contrib import admin
#from django.conf.urls import path
from django.conf.urls import include,url
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
import blog.urls

sitemaps={
    'posts':PostSitemap
}
urlpatterns = [
    url('admin/', admin.site.urls),
    url('blog/', include('blog.urls',namespace='blog')),
    url('^sitemap\.xml$',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),

]

第三章/blog/models.py
from django.db import models
from django.utils import  timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')
class Post(models.Model):
    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','Published'),
    )
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,related_name='blog_posts',on_delete=models.CASCADE)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now())
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects=models.Manager()
    published=PublishedManager()
    tags=TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=(self.publish.year,
                              self.publish.strftime('%m'),
                              self.publish.strftime('%d'),
                              self.slug,))
    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return  self.title

class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return  'Comment by {} on {}'.format(self.name,self.post)




第三章/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name= forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

class SearchForm(forms.Form):
    query=forms.CharField()

第三章/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm,SearchForm
from django.core.mail import send_mail
from mysite import settings
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet
# Create your views here.
def post_list(request,tag_slug=None):
    obj_list=Post.published.all()
    tag=None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        obj_list=obj_list.filter(tags__in=[tag])
    pagnator=Paginator(obj_list,3)
    page=request.GET.get('page')
    try:
        posts=pagnator.page(page)
    except PageNotAnInteger:
        posts=pagnator.page(1)
    except EmptyPage:
        posts=pagnator.page(pagnator.num_pages)
    return render(request,'blog/post/list.html',{'page':page,'posts':posts,'tag':tag})

def post_detail(request,year,month,day,post):
    post=get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    comments=post.comments.filter(active=True)
    new_comment = None
    post_tags_ids=post.tags.values_list('id',flat=True)
    similar_posts=Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tag=Count('tags')).order_by('-same_tag','-publish')[:4]
    if request.method=='POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form=CommentForm()
    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form,'similar_posts':similar_posts})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_share(request,post_id):
    sent = False
    post=get_object_or_404(Post,id=post_id,status='published')
    if request.method=='POST':
        form =EmailPostForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{} {} recommends you reading "{}"'.format(data['name'],data['email'],post.title)
            message='Read "{}" at {} \n\n{} comments: {}'.format(post.title,post_url,data['name'],data['comments'])
            send_mail(subject,message,settings.EMAIL_HOST_USER,[data['to']])
            sent=True
    else:
        form=EmailPostForm()

    return  render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

def post_search(request):
    form=SearchForm()
    if 'query' in request.GET:
        form=SearchForm(request.GET)
        if form.is_valid():
            data=form.cleaned_data
            results=SearchQuerySet().models(Post).filter(content=data['query']).load_all()
            total_results =results.count()
    else:
        data=None
        results=None
        total_results=None
    return render(request,'blog/post/search.html',{'form':form,'data':data,'results':results,'total_results':total_results})

第三章/blog/templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
  <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="{%  static "css/bootstrap-theme.css" %}" rel="stylesheet">
  <!-- Bootstrap Core JavaScript -->
    <script src="{% static  "js/bootstrap.min.js" %}"></script>
</head>
<body>
<div id="content" class="col-lg-8" >
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar" class="col-lg-4">
    <h2>MY blog</h2>
    <p>this is zhosuc blog. I've written <b>{% total_posts %}</b> posts so far</p>
<p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a> </p>
    <h3>Latest Posts</h3>
    {% show_latest_posts 2 %}
    <h2>Most commented posts</h2>

    <ul>
        {% for post in most_comments %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

第三章/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_num }}">Previous</a>
        {% endif %}
    <span class="current">
        Page{{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

第三章/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<H1>{{ post.title }}</H1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
    <p>
    <a href="{%  url "blog:post_share" post.id %}">Share</a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <P><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></P>
    {% empty %}
    NO simlar posts yet
    {% endfor %}
    {% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There aare no comments yet.</p>
    {% endfor %}
    {%  if new_comment %}
    <h2>Your comment has been added</h2>
    {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
    {{ comment_form.as_p }}
    {%  csrf_token %}
    <p><input type="submit" value="Add comment" ></p>
    </form>
    {% endif %}

{% endblock %}

第三章/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

第三章/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog {% endblock %}

{% block content %}
<h1>Zhousc</h1>
    {%  if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
    <p class="tags">Tags:{{ post.tage }}
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag"  tag.slug %}">
        {{ tag.name }}
    </a>
    {%  if not forloop.last %},{% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatechars_html:30}}
{% endfor %}
    {% include "blog/pagination.html" with page=posts %}
{% endblock %}

第三章/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{%  load highlight %}
{%  load staticfiles %}
{% block title %}Search {% endblock %}
{% block content %}
{% if "query" in request.GET %}
<h1>Posts containing"{{ data.query}}"</h1>
<h3>Found{{ total_results }} result{{ total_results|pluralize }}</h3>
{%  for result in results %}
   {% with post=result.object %}
    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h4>
     {{ post.body|truncatewords:5 }}
  {% endwith %}
{% empty %}
   <p>No result for your query</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Search again</a> </p>
{% else %}
   <h1>Seach for Posts</h1>
    <form action="." method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
{% endif %}
{% endblock %}

第三章/blog/templates/blog/post/share.html
{%  extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}
{%  if sent %}
 <h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}' was successfully sent to {{ data.to }}
</p>
{% else %}
<h1>Share"{{ post.title }}" by E-mail</h1>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send Email">
</form>
{% endif %}
{% endblock %}